services:
  spica2:
    build:
      context: ..
      dockerfile: docker/dockerfile   # NOTE: lowercase to match your uploaded file
    container_name: spica2
    shm_size: '2gb'

    ports:
      - '50002:8888'   # Host 50002 -> Container 8888 (Jupyter)
      - '8097:8097'    # Visdom

    volumes:
      - ../:/workspace
      # Use DATASET_PATH if provided, otherwise default to a repo-local ../DataSet directory
      - type: bind
        source: ${DATASET_PATH:-../DataSet}
        target: /workspace/DataSet

    working_dir: /workspace
    command: >
      jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --no-browser
